### ISSUE TITLE
Inconsistencies with UG command guidelines with application feedback

### ISSUE THREAD

**Issue by chwoozy** [AY2021S2-CS2103T-T11-1/tp#136]
Inconsistencies found in some commands.
e.g. (In the UG, the parameter name for a student's phone number is `STUDENT_PHONE_NUMBER` whereas in `EditStudentCommand`, `PHONE`)

**Comment by JonahhGohh** [comment]
To add on: 
`add_rec_session n/STUDENT_NAME d/START_DATE e/END_DATE b/INTERVAL t/TIME k/DURATION s/SUBJECT f/FEE`
vs `e/` and `b/` at the back for the actual command message for add_rec_session

**Comment by enhao25** [comment]
Both examples has been solved.
