### ISSUE TITLE
Check overlapping session for recurring sessions

### ISSUE THREAD

**Issue by chwoozy** [AY2021S2-CS2103T-T11-1/tp#139]

**Comment by samleewy** [comment]
![image](https://user-images.githubusercontent.com/45890870/112827349-cbaa7a80-90c0-11eb-8712-bc2f74e679dc.png)

Tom was added first with:
start time: 12:00
duration: 1hour

Samuel Lee was added second with:
start time: 11:00
duration: 2hours

Should conflict, but didn't. KIV.

**Comment by chwoozy** [comment]
Resolved in #150
