### ISSUE TITLE
UG: Naming of section for fees

### ISSUE THREAD

**Issue by samleewy** [AY2021S2-CS2103T-T11-1/tp#91]
In relation with #85, discuss on whether it should be a "Fees" section or "Others" section.

@enhao25:
> Haha yeah I tot of before, but then I think at most there will only be 2 commands, one to get monthly fee for a particular month, one to get past 3 months fee. So not sure if it should be a section by itself. Although I think doesn't hurt to change ba. I will make the changes first then.

**Comment by JonahhGohh** [comment]
I think having at "Fees" is fine.
![image](https://user-images.githubusercontent.com/39006568/112336098-bbc51c00-8cf7-11eb-81e2-04eb5b833e74.png)

**Comment by enhao25** [comment]
Ok! I think it shouldn't affect much, so just leaving it as fees should be fine.
